#! /bin/sh

err () {
	echo "$1"
	cd $WD
	exit 1
}

# Store current work dir
WD="$(pwd)"

# Get into /cit
cd /cit

# Err if it's impossible to cd to /cit

if [ $? -ne 0 ]; then
	err "FATAL: cit directory is in the wrong location: expected at /cit"
fi

# Create config directories
mkdir ~/.config
mkdir ~/.config/openbox ~/.config/dunst ~/.config/tint2 ~/.config/cit
# Copy config files
cp ./openbox.autostart ~/.config/openbox/autostart
cp ./openbox.environment ~/.config/openbox/environment
cp ./openbox.menu.xml ~/.config/openbox/menu.xml
cp ./openbox.rc.xml ~/.config/openbox/rc.xml
cp ./dunst.dunstrc ~/.config/dunst/dunstrc
cp ./tint2.tint2rc ~/.config/tint2/tint2rc

# See if ~/.config/cit/env3 dir exists and set it up if required, installing Python depends using pip

if ! test -d ~/.config/cit/env3; then
	python3 -m venv ~/.config/cit/env3
	if [ $? -ne 0 ]; then
		err "FATAL: Failed to create a Python virtual environment"
	fi
	source ~/.config/cit/env3/bin/activate
	if [ $? -ne 0 ]; then
		err "FATAL: failed to activate env3 virtual environment"
	fi
	pip install -r requirements.txt
	if [ $? -ne 0 ]; then
		err "FATAL: pip failed installing from requirements.txt"
	fi
fi

# Return to original work dir
cd $WD

